name: $(major).$(minor).$(patch)

trigger:
- master

pr: none

variables:
  major: 1
  minor: 0
  patch: $[counter('versioncounter', 1)]

jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-18.04'
    strategy:
      matrix:
        Janus:
          stage.name: 'janus'
          label.name: 'fruitnanny-janus'
          container.name: 'ivadim/fruitnanny-janus'
        GStreamer:
          stage.name: 'gstreamer'
          label.name: 'fruitnanny-gstreamer'
          container.name: 'ivadim/fruitnanny-gstreamer'
        Fruitnanny:
          stage.name: 'fruitnanny'
          label.name: 'fruitnanny-app'
          container.name: 'ivadim/fruitnanny-app'
      maxParallel: 3
    steps:
      - script: |
          docker version
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
          docker build . -f docker/$(stage.name)/Dockerfile -t $(container.name)
          docker images
          docker inspect $(container.name)
        displayName: 'Build $(stage.name) Container'

      - script: |
          docker image save $(container.name) -o $(Build.ArtifactStagingDirectory)/$(label.name)-v$(Build.BuildNumber).tgz
        displayName: 'Export $(stage.name) Container Image'

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          artifactName: images